# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  python: circleci/python@0.2.1

references:
  python_ver: &python_ver
    circleci/python:3.7

defaults: &defaults
  docker:
    - image: *python_ver
  working_directory: ~/web-platform-contribution-guide

commands:
  setup_steps:
    steps:
      - checkout
      - python/install-deps

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            ./lint.sh
  build:
    <<: *defaults
    steps:
      - setup_steps
      - run: make dirhtml
      - persist_to_workspace:
          root: build
          paths: html

  deploy-pages:
    docker:
      - image: node:12
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run:
          name: Disable jekyll builds
          command: touch build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@web-platform-contributing-guide.doc"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "8a:f6:29:f9:b3:9f:b5:1a:fd:b8:44:2e:c5:cc:4a:91"
      # Temporarily disabled so that the wpc.guide domain could be prepared
      # and verified without making the site public.
      #- run:
      #    name: Deploy docs to gh-pages branch
      #    command: gh-pages --dotfiles --message "[skip ci] Updates" --dist build/html

workflows:
  version: 2.1
  "Lint, Build and Deploy":
    jobs:
      - lint
      - build:
          requires:
            - lint
      - deploy-pages:
          requires:
            - build
          filters:
            branches:
              only: master
