# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  python: circleci/python@0.2.1

references:
  python_ver: &python_ver
    circleci/python:3.7

defaults: &defaults
  docker:
    - image: *python_ver
  working_directory: ~/web-platform-contribution-guide

commands:
  setup_steps:
    steps:
      - checkout
      - python/install-deps

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            ./lint.sh
  build:
    <<: *defaults
    steps:
      - setup_steps
      - run: make html

workflows:
  version: 2.1
  "Lint and Build":
    jobs:
      - lint
      - build:
          requires:
            - lint
